services:
  api:
    build:
      context: .
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./application/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - app-network
    volumes:
      - ./application/grafana/provisioning:/etc/grafana/provisioning

networks:
  app-network:
    driver: bridge

volumes:
  prometheus_data:
    driver: local
