services:
  api:
    build:
      context: .
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./application/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - app-network
    volumes:
      - ./application/grafana/provisioning:/etc/grafana/provisioning

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pocdefender
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  prometheus_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
