{
 "title": "POC Defender Dashboard",
 "description": "A quickstart to setup the Prometheus Go runtime exporter with preconfigured dashboards, alerting rules, and recording rules.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "label_values(go_info, job)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(go_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Reserved Memory",
   "type": "graph",
   "description": "Average total bytes of memory reserved across all process instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by(job)(go_memstats_sys_bytes{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}} (avg)"
    }
   ]
  },
  {
   "title": "Stack Memory Use",
   "type": "graph",
   "description": "Average stack memory usage across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (job) (go_memstats_stack_sys_bytes{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: stack inuse (avg)"
    }
   ]
  },
  {
   "title": "Other Memory Reservations",
   "type": "graph",
   "description": "Average memory reservations by the runtime, not for stack or heap, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (job)(go_memstats_mspan_sys_bytes{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: mspan (avg)"
    },
    {
     "expr": "avg by (job)(go_memstats_mcache_sys_bytes{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: mcache (avg)"
    },
    {
     "expr": "avg by (job)(go_memstats_buck_hash_sys_bytes{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: buck hash (avg)"
    },
    {
     "expr": "avg by (job)(go_memstats_gc_sys_bytes{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: gc (avg)"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "description": "Average memory reserved, and actually in use, by the heap, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (job)(go_memstats_heap_sys_bytes{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: heap reserved (avg)"
    },
    {
     "expr": "avg by (job)(go_memstats_heap_inuse_bytes{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: heap in use (avg)"
    },
    {
     "expr": "avg by (job)(go_memstats_heap_alloc_bytes{job=~\"tns_app\",instance=~\".*\"})",
     "legendFormat": "{{job}}: heap alloc (avg)"
    },
    {
     "expr": "avg by (job)(go_memstats_heap_idle_bytes{job=~\"tns_app\",instance=~\".*\"})",
     "legendFormat": "{{job}}: heap idle (avg)"
    },
    {
     "expr": "avg by (job)(go_memstats_heap_released_bytes{job=~\"tns_app\",instance=~\".*\"})",
     "legendFormat": "{{job}}: heap released (avg)"
    }
   ]
  },
  {
   "title": "Allocation Rate, Bytes",
   "type": "graph",
   "description": "Average allocation rate in bytes per second, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (job)(rate(go_memstats_alloc_bytes_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}}: bytes malloced/s (avg)"
    }
   ]
  },
  {
   "title": "Heap Object Allocation Rate",
   "type": "graph",
   "description": "Average rate of heap object allocation, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{job}}: obj mallocs/s (avg)"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "description": "Average number of live memory objects across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(job)(go_memstats_mallocs_total{job=\"$job\", instance=~\"$instance\"} - go_memstats_frees_total{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: object count (avg)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "Average number of goroutines across instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (job)(go_goroutines{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: goroutine count (avg)"
    }
   ]
  },
  {
   "title": "GC min & max duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (job)(go_gc_duration_seconds{quantile=\"0\", job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: min gc time (avg)"
    },
    {
     "expr": "avg by (job)(go_gc_duration_seconds{quantile=\"1\", job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: max gc time (avg)"
    }
   ]
  },
  {
   "title": "Next GC, Bytes",
   "type": "graph",
   "description": "The number used bytes at which the runtime plans to perform the next GC, averaged across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (job)(go_memstats_next_gc_bytes{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}} next gc bytes (avg)"
    }
   ]
  }
 ]
}